require("plugin-config.colorschema")
require("plugin-config.lualine")
require("plugin-config.nvim-tree")
require("plugin-config.treesitter")
require("plugin-config.telescope")
require("plugin-config.lsp")
require("plugin-config.comment")
require("plugin-config.lsp-lines")
require("plugin-config.indent-blankline")
require("plugin-config.cmp")
require("plugin-config.gitsigns")

